[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
remappings = ['foundry-huff/=lib/foundry-huff/src']
ffi =true 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
